### ISSUE TITLE
Drop RxSwift support

### ISSUE THREAD

**Issue by subdan** [RedMadRobot/apexy-ios#34]
@Alexander-Ignition, @modestman, @laqiguy, Hello.

I want to drop RxSwift support for the following reasons:
1. When connecting Apexy via SPM RxSwift dependency downloading and indexing even if `ApexyRxSwift` library not chosen.
2. Developers migrated from RxSwift to Combine

What do you think?

**Comment by modestman** [comment]
I agree that RxSwift support can be removed

**Comment by Alexander-Ignition** [comment]
I agree
I think it's not difficult to make yourself a wrapper if necessary
